# Naive Bayes Example

In [71]:
# Library Imports

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [72]:
DataSet_imdb = pd.DataFrame()
DataSet_imdb["Text"] = pd.read_csv('Naive Bayes Data/imdb_labelled.txt', sep = "\t", header = None)[0]
DataSet_imdb["Score"] = pd.read_csv('Naive Bayes Data/imdb_labelled.txt', sep = "\t", header = None)[1].astype(int)

DataSet_imdb.tail()

Text  Score
743  I just got bored watching Jessice Lange take h...      0
744  Unfortunately, any virtue in this film's produ...      0
745                   In a word, it is embarrassing.        0
746                               Exceptionally bad!        0
747  All in all its an insult to one's intelligence...      0

In [73]:
DataSet_yelp = pd.DataFrame()

DataSet_yelp["Text"] = pd.read_csv('Naive Bayes Data/yelp_labelled.txt', sep = '\t', header=None)[0]
DataSet_yelp["Score"] = pd.read_csv('Naive Bayes Data/yelp_labelled.txt', sep = '\t', header=None)[1]

DataSet_yelp.describe()

Score
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

In [74]:
DataSet_amazon = pd.DataFrame()

DataSet_amazon["Text"] = pd.read_csv('Naive Bayes Data/amazon_cells_labelled.txt', sep = '\t', header=None)[0]
DataSet_amazon["Score"] = pd.read_csv('Naive Bayes Data/amazon_cells_labelled.txt', sep = '\t', header=None)[1]

DataSet_amazon.describe()

Score
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

In [75]:
DataSet = DataSet_imdb.append(DataSet_yelp, ignore_index = True).append(DataSet_amazon, ignore_index = True)

DataSet.describe()

Score
count  2748.000000
mean      0.504367
std       0.500072
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [76]:
count_vectorizer = CountVectorizer(binary='true')

In [77]:
Training_Docs = DataSet["Text"]

Training_Score = DataSet["Score"]

In [78]:
Training_Docs = count_vectorizer.fit_transform(Training_Docs)

Training_Docs

<2748x5155 sparse matrix of type '<class 'numpy.int64'>'
	with 30275 stored elements in Compressed Sparse Row format>

In [79]:
print (Training_Docs[0])

  (0, 2764)	1
  (0, 5139)	1
  (0, 1401)	1
  (0, 1331)	1
  (0, 75)	1
  (0, 2954)	1
  (0, 166)	1
  (0, 2956)	1
  (0, 4133)	1
  (0, 4890)	1


In [80]:
print (Training_Docs[0])

  (0, 2764)	1
  (0, 5139)	1
  (0, 1401)	1
  (0, 1331)	1
  (0, 75)	1
  (0, 2954)	1
  (0, 166)	1
  (0, 2956)	1
  (0, 4133)	1
  (0, 4890)	1


In [81]:
# Training Phase

from sklearn.naive_bayes import BernoulliNB

classifier = BernoulliNB().fit(Training_Docs,Training_Score)

In [87]:
# Test Phase

classifier.predict(count_vectorizer.transform([
    "It's hard to dislike Grant Gustin, who has such a natural charisma, but the show surely tried. Now, it's letting him have fun again with inventive speedster sequences, new ways of battling foes, as well as familiar interactions among the team."
]))

array([1])

In [88]:
classifier.predict(count_vectorizer.transform([
    "Perhaps I'm the only one who feels this way, but the decision to dispense with the meat of the story to skip to the end seems pretty familiar, no?"                     
]))

array([0])

In [ ]:
# Here we used actual reviews from rotten tomoates and it came out correct for both!!

# Original Tutorial

In [61]:
with open("Naive Bayes Data/imdb_labelled.txt", "r") as text_file: 
    lines = text_file.read().split('\n')

In [62]:
lines[0:3]

['A very, very, very slow-moving, aimless movie about a distressed, drifting young man.  \t0',
 'Not sure who was more lost - the flat characters or the audience, nearly half of whom walked out.  \t0',
 'Attempting artiness with black & white and clever camera angles, the movie disappointed - became even more ridiculous - as the acting was poor and the plot and lines almost non-existent.  \t0']

In [63]:
with open("Naive Bayes Data/yelp_labelled.txt", "r") as text_file: 
    lines += text_file.read().split('\n')
with open("Naive Bayes Data/amazon_cells_labelled.txt", "r") as text_file: 
    lines += text_file.read().split('\n')  

In [64]:
lines = [line.split("\t") for line in lines if len(line.split("\t"))==2 and line.split("\t")[1] != ''] 

In [65]:
lines[0:3]

[['A very, very, very slow-moving, aimless movie about a distressed, drifting young man.  ',
  '0'],
 ['Not sure who was more lost - the flat characters or the audience, nearly half of whom walked out.  ',
  '0'],
 ['Attempting artiness with black & white and clever camera angles, the movie disappointed - became even more ridiculous - as the acting was poor and the plot and lines almost non-existent.  ',
  '0']]

In [67]:
train_documents = [line[0] for line in lines ]
train_documents[0:3]

['A very, very, very slow-moving, aimless movie about a distressed, drifting young man.  ',
 'Not sure who was more lost - the flat characters or the audience, nearly half of whom walked out.  ',
 'Attempting artiness with black & white and clever camera angles, the movie disappointed - became even more ridiculous - as the acting was poor and the plot and lines almost non-existent.  ']

In [68]:
train_labels = [int(line[1]) for line in lines]
train_labels[0:3]

[0, 0, 0]

In [69]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
count_vectorizer = CountVectorizer(binary='true')
train_documents = count_vectorizer.fit_transform(train_documents)

In [10]:
train_documents

<3000x5155 sparse matrix of type '<type 'numpy.int64'>'
	with 31578 stored elements in Compressed Sparse Row format>

In [11]:
print train_documents[0]

  (0, 4890)	1
  (0, 4133)	1
  (0, 2956)	1
  (0, 166)	1
  (0, 2954)	1
  (0, 75)	1
  (0, 1331)	1
  (0, 1401)	1
  (0, 5139)	1
  (0, 2764)	1


In [12]:
# Training Phase
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB().fit(train_documents,train_labels)

In [13]:
# Test Phase
classifier.predict(count_vectorizer.transform(["this is the best movie"]))

array([1])

In [14]:
classifier.predict(count_vectorizer.transform(["this is the worst movie"]))

array([0])